FROM golang AS build

WORKDIR /go/src/github.com/ebauman/moo

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o agent.out ./agent

FROM alpine:latest

COPY --from=build /go/src/github.com/ebauman/moo/agent.out ./agent

RUN chmod +x ./agent

CMD ["./agent"]