apiVersion: v1
kind: Namespace
metadata:
  name: moo-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moo-agent-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moo-agent
  namespace: moo-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moo-agent-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: moo-agent-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: moo-agent
    namespace: moo-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moo-agent
  namespace: moo-agent
spec:
  selector:
    matchLabels:
      app: moo-agent
  template:
    metadata:
      labels:
        app: moo-agent
    spec:
      serviceAccountName: moo-agent
      containers:
        - name: moo-agent
          image: ebauman/moo-agent:v0.0.1
          env:
            - name: RANCHER_URL
              value: ""
            - name: RANCHER_ACCESS_KEY
              value: ""
            - name: RANCHER_SECRET_KEY
              value: ""
            - name: MOO_CLUSTER_NAME
              value: ""