apiVersion: v1
kind: Namespace
metadata:
  name: moo-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moo-agent-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moo-agent
  namespace: moo-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moo-agent-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: moo-agent-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: moo-agent
    namespace: moo-agent
---
apiVersion: batch/v1
kind: Job
metadata:
  name: moo-agent
  namespace: moo-agent
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: moo-agent
      restartPolicy: Never
      containers:
        - name: moo-agent
          image: ebauman/moo-agent:v0.1.0
          env:
            - name: RANCHER_URL
              value: "https://demo-hosted.rancher.cloud/v3"
            - name: RANCHER_ACCESS_KEY
              value: "token-rst4r"
            - name: RANCHER_SECRET_KEY
              value: "52skmn9s8bwjg4hddj7qlmsbsgp29nrg8qm8wnpgf2lgjgs5c78g6w"
            - name: MOO_CLUSTER_NAME
              value: "moo-testing"